### ISSUE TITLE
Issue with APP_WEBHOOK_SECRET Environment Variable Not Being Recognized During Build

### ISSUE THREAD

**Issue by JanusChoi** [astriaai/headshots-starter#105]
Hello,

I am encountering an issue when deploying an application on Vercel, where the build process fails due to the `APP_WEBHOOK_SECRET` environment variable apparently not being recognized or found, despite being set.

Here's the error message I receive during deployment:

```
Error: MISSING APP_WEBHOOK_SECRET!
    at 46379 (/vercel/path0/.next/server/app/astria/prompt-webhook/route.js:1:1562)
    ...
> Build error occurred
Error: Failed to collect page data for /astria/prompt-webhook
    ...
```

I have confirmed that the `APP_WEBHOOK_SECRET` is a randomly generated string (in this case, "yousayitsafuckingrandomstring?") as suggested in the documentation/README, and I've made sure to set it correctly in the project settings on Vercel.

Here are the steps I've taken to troubleshoot without success:

1. Double-checked that the environment variable is set in the Vercel project settings.
2. Ensured that the variable is being correctly referenced in the code using `process.env.APP_WEBHOOK_SECRET`.
3. Attempted to deploy with a simpler value for the environment variable to rule out issues with special characters.
4. Reviewed the Vercel documentation and existing issues for any similar cases or additional configuration steps I might have missed.

I am wondering if there are any known issues with environment variable recognition during the build phase on Vercel, or if there are additional steps I need to take to ensure the environment variable is correctly passed and recognized by the build environment.

Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by fred3105** [comment]
Hey Janus,

I'm also having issues with Astria's callbacks, I would suggest double checking astria/train-model/route.ts and make sure that your callback url contains &webhook_secret=${appWebhookSecret}

If the url is correct, the problem likely comes from Astria. Are you using the mock environment for Astria or the production environment ?

**Comment by suifeng8619** [comment]
You need to add the APP_WEBHOOK_SECRET and ASTRIA_API_KEY fields in the background

**Comment by matr1xp** [comment]
Same issue here, tried adding variables in Vercel's Environment variables dashboard, re-run the deployment and it still fails with error:
`Error: MISSING APP_WEBHOOK_SECRET!
    at 46379 (/vercel/path0/.next/server/app/astria/prompt-webhook/route.js:1:1562)`
Please fix. Thank you.

**Comment by SnoochiMink** [comment]
![error1](https://github.com/user-attachments/assets/fb88d386-405b-4503-9d7b-2a4d2606bb37)
same here
